using System;
using System.Collections.Generic;
using System.Text;

namespace Copy_CreatureRandomness.Chanpionship
{
    public static class Utilities
    {
        private static readonly List<string> names = new List<string>
        {
            "1.",
            "2.",
            "3.",
            "4.",
            "5.",
            "6.",
            "7.",
            "8.",
            "10.",
            "11.",
            "12.",
            "13.",
            "14.",
            "155.",
            "16.",
            "17.",
            "18.",
            "19.",
            "20.",
            "21.",
            "22.",
            "23.",
            "24.",
            "25.",
            "26.",
            "27.",
            "28.",
            "29.",
            "30.",
            "31.",
            "32.",
            "33.",
            "34.",
            "35.",
            "36.",
            "37.",
            "38.",
            "39.",
            "40.",
            "41.",
            "42.",
            "43.",
            "44.",
            "45.",
            "46.",
            "47.",
            "48.",
            "49.",
            "50.",
            "51.",
            "52.",
            "53.",
            "54.",
            "55.",
            "56.",
            "57.",
            "58.",
            "59.",
            "60.",
            "61.",
            "62.",
            "63.",
            "64.",
            "65.",
            "66.",
            "67.",
            "68.",
            "69.",
            "70.",
            "72.",
            "73.",
            "74.",
            "75.",
            "76.",
            "77.",
            "78.",
            "79.",
            "80.",
            "81.",
            "82.",
            "02.",
            "Cattra",
            "Chara",
            "Drago",
            "Hisoka",
            "Mikuu",
            "Miran",
            "Neferphito",
            "Yuzuki",
            "Zack",
            "147.",
            "164.",
            "176.",
            "Ala",
            "Asriel",
            "BattleFire",
            "Butcher",
            "Electro",
            "Iris",
            "Jax",
            "Juigalag",
            "Katia",
            "Luculia",
            "Maph",
            "Metheus",
            "Oblivian",
            "Sailas",
            "Sheogoraph",
        };

        public static List<string> GetNames()
        {
            return names;

        }

        public static int GetRandom(int bottom, int top)
        {
            Random random = new Random();
            return random.Next(bottom, top);
        }
    }
}
